services:
  - type: web
    name: django-fitness-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn fitness_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: fitness_tracker_t5b4
          property: connectionString
